### ISSUE TITLE
angular 2+ support

### ISSUE THREAD

**Issue by Ahmed-Habbachi** [adamgibbons/ics#127]
does anyone succeed to make it working in angular? how?

**Comment by phoulgaux** [comment]
I am working on an Angular 7 app. I discovered that `ics` has an implicit dependency of `net` (built-in Node module) via [`@hapi/joi`](https://github.com/hapijs/joi). Hopefully, the issue is purely TypeScript-related.

As far as I can see, this module is used in `@hapi/joi` only for the `hostname` validator which is not used by `ics` (@adamgibbons could you confirm?). However, unless I missed something, `@hapi/joi` no longer uses `net` starting from version `16`.

Knowing that, a version bump to the `@hapi/joi` dependency should make it usable in browser.

So far I didn't find a way to get a workaround without version bumping other than providing a custom Webpack config. In such a case, this issue might be helpful: https://github.com/jmesnil/stomp-websocket/issues/119

Cheers 😉

**Comment by phoulgaux** [comment]
@adamgibbons @Ahmed-Habbachi
You can take a look at this PR: https://github.com/adamgibbons/ics/pull/139. It seems I got it working on Angular application by updating Joi

**Comment by adamgibbons** [comment]
#139 is published - many thanks @phoulgaux 🙏  

Please reopen is this issue persists.
