### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by cavinsmith** [adamgibbons/ics#52]
How to use input time in particular timezone?
I can convert time to local timezone, but best way for me is to leave it in original timezone and use this for calendar

**Comment by heyfrench** [comment]
@adamgibbons I need this soon and have time to work on it. I threw together quick support for a `timezone` prop that adds the `TZID`, but quickly learned that's not enough in some clients without the corresponding `VTIMEZONE` definitions. 

Do you have any thoughts on how you'd like this to be implemented? Do you want to include common timezone defs with the library, or just expose an API for defining them and referencing them in events?

**Comment by adamgibbons** [comment]
@heyfrench Awesome - this will be a really nice addition to the library. I'm leaning toward including common timezone defs because it's just so much more user-friendly. I know there are a ton of them - but just getting the most common in is a big win and they'll trickle in over time, especially if we include a section in the readme w/ a template for how they're laid out. What do you think?

**Comment by heyfrench** [comment]
I agree. Hoping to have some time to dig in this weekend.

**Comment by iSuslov** [comment]
How are you guys doing?

**Comment by heyfrench** [comment]
@iSuslov I ended up writing a new ICS builder from the ground up with timezone support from the start. I'm gonna open source it, but I haven't had time for documentation and learning how to package and publish things for NPM yet. It doesn't have all of the features yet that this one does (like alarms and such), but it's got good test coverage and is flowtyped throughout. 

I'll see if I can at least get it up on GH this weekend. Do you have any experience with NPM packaging, or might you have time to hook up CI if I get it posted with some basic documentation?
